global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: myapp
    scrape_interval: 5s
    static_configs:
      - targets: ["172.17.0.1:3001"]