 global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['prometheus:9100']
  - job_name: 'mysqld-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']
  - job_name: 'myapp'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:3001']